library(sf)
library(terra)
Elev5km. = rast('wc2.1_2.5m_elev/wc2.1_2.5m_elev.tif')
Elev1km. = rast('C:/a/geo/climate/wc2.1_30s_elev/wc2.1_30s_elev.tif')
altrast <- rast('C:/a/geo/dem/alt_30s_esri/alt/w001001.adf')

outer = matrix(c(-72,-30.5,-72,-24.5,-69.5,-24.5,-69.5,-30.5,-72,-30.5),ncol=2, byrow=TRUE)
pts = list(outer)
nullbox <- sf::st_polygon(pts)
nullbox <- sf::st_sfc(nullbox)
nullbox <- sf::st_sf(nullbox, crs=crs(Elev5km))
nullbox$val <- 1
plot(nullbox)
nullbox <- vect(nullbox)
altrast2 <- crop(altrast, nullbox)
plot(altrast2)
Elev1km <- merge(Elev1km., altrast2)
writeRaster(Elev1km, 'output/Elev1km.tif', overwrite=T)
Elev.res <- aggregate(Elev1km, fact=5, fun=mean)
Elev.res <- crop(Elev.res, nullbox)
plot(Elev.res)
Elev5km <- merge(Elev5km., Elev.res)
writeRaster(Elev5km, 'output/Elev5km.tif', overwrite=T)